apiVersion: v1
kind: Service
metadata:
  name: mywebapp-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: mywebapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000 # Port eksternal untuk akses

